/* Generated by Yosys 0.9+4052 (git sha1 0ccc7229c, clang 11.0.1-2 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "test_mux.v:1.1-8.10" *)
module test(a, b, s, c, r);
  (* src = "test_mux.v:3.5-3.17" *)
  wire _0_;
  (* src = "test_mux.v:6.12-6.21" *)
  wire _1_;
  (* src = "test_mux.v:1.19-1.20" *)
  input a;
  (* src = "test_mux.v:1.28-1.29" *)
  input b;
  (* src = "test_mux.v:1.47-1.48" *)
  output c;
  (* src = "test_mux.v:1.57-1.58" *)
  output r;
  (* src = "test_mux.v:3.5-3.10" *)
  wire r_reg;
  (* src = "test_mux.v:1.37-1.38" *)
  input s;
  assign _1_ = s ? (* src = "test_mux.v:6.12-6.21" *) a : b;
  assign r = r_reg;
  assign c = _1_;
  assign _0_ = 1'h0;
  assign r_reg = 1'h0;
endmodule
