/* Generated by Yosys 0.9+4052 (git sha1 0ccc7229c, clang 11.0.1-2 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "test_mux.v:1.1-11.10" *)
module test(a, b, s, clk, c, r);
  (* src = "test_mux.v:8.1-9.16" *)
  wire _0_;
  (* src = "test_mux.v:3.5-3.17" *)
  wire _1_;
  (* src = "test_mux.v:6.12-6.21" *)
  wire _2_;
  (* src = "test_mux.v:1.19-1.20" *)
  input a;
  (* src = "test_mux.v:1.28-1.29" *)
  input b;
  (* src = "test_mux.v:1.58-1.59" *)
  output c;
  (* src = "test_mux.v:1.46-1.49" *)
  input clk;
  (* src = "test_mux.v:1.68-1.69" *)
  output r;
  (* src = "test_mux.v:3.5-3.10" *)
  reg r_reg = 1'h0;
  (* src = "test_mux.v:1.37-1.38" *)
  input s;
  (* src = "test_mux.v:8.1-9.16" *)
  always @(posedge clk)
    r_reg <= a;
  assign _2_ = s ? (* src = "test_mux.v:6.12-6.21" *) a : b;
  assign r = r_reg;
  assign c = _2_;
  assign _1_ = 1'h0;
  assign _0_ = a;
endmodule
