/* Generated by Yosys 0.9+4052 (git sha1 0ccc7229c, clang 11.0.1-2 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "test_mux.v:1.1-5.10" *)
module test(a, b, s, c);
  (* src = "test_mux.v:3.12-3.21" *)
  wire _0_;
  (* src = "test_mux.v:1.19-1.20" *)
  input a;
  (* src = "test_mux.v:1.28-1.29" *)
  input b;
  (* src = "test_mux.v:1.47-1.48" *)
  output c;
  (* src = "test_mux.v:1.37-1.38" *)
  input s;
  assign _0_ = s ? (* src = "test_mux.v:3.12-3.21" *) a : b;
  assign c = _0_;
endmodule
